name: GAN
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - pytest
  - optuna
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu128
    - torchvision --index-url https://download.pytorch.org/whl/cu128
