"""
module of helper functions for this project
"""
from typing import Type, Callable
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
from .models import Discriminator, Generator


def make_dataloader(
    X: torch.Tensor,
    c: torch.Tensor | None = None,
    batch_size: int = 64,
    shuffle: bool = True,
):
    """
    function to turn data into a DataLoader
    Parameters
    X : torch.Tensor
        input data
    c : Optional torch.Tensor
        For a conditional GAN/WGAN, the condtional tensor
    batch_size: int
        batch size for the DataLoader
    shuffle : bool
        shuffle parameter for DataLoader
    Returns
    -------
    DataLoader
        DataLoader from X and optionally c
    """
    if c is not None:
        dataset = TensorDataset(X, c)
    else:
        dataset = TensorDataset(X)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)


def gradient_penalty(
    D: Discriminator,
    x_real: torch.Tensor,
    x_fake: torch.Tensor,
    c: torch.Tensor | None = None,
    lambda_gp: float = 10.0,
):
    """
    function to compute gradient penalty for WGAN-GP
    Parameters
    ----------
    D: Discriminator
        the critic for the model
    x_real : torch.Tensor
        a tensor of real data
    x_fake : torch.Tensor
        a tensor of data from the Generator
    c: Optional torch.Tensor
        for a condtional WGAN-GP, the conditional tensor
    lambda_gp : float
        multiplier used to compute the penalty
    """
    batch_size = x_real.size(0)
    # interpolate a random point between x_real and x_fake
    eps = torch.rand(batch_size, 1, device=x_real.device)
    eps = eps.expand_as(x_real)
    x_hat = eps * x_real + (1 - eps) * x_fake
    x_hat.requires_grad_(True)
    # get the critic score for x_hat
    d_hat = D(x_hat, c)
    # get partial derivative of d_hat with respect to x_hat
    grads = torch.autograd.grad(
        outputs=d_hat,
        inputs=x_hat,
        grad_outputs=torch.ones_like(d_hat),
        create_graph=True,
        retain_graph=True,
        only_inputs=True,
    )[0]
    # compute how badly the critic violates the Lipshcitz constraint along x_hat
    grads = grads.view(batch_size, -1)
    gp = ((grads.norm(2, dim=1) - 1) ** 2).mean()
    # multiply by lambda_gp
    return lambda_gp * gp

def load_gan_checkpoint(
    path: str,
    generator_cls:Type[nn.Module] = Generator,
    discriminator_cls:Type[nn.Module] = Discriminator,
    map_location: Callable | str | dict | None = None,
):
    """
    function to read in saved models
    Parameters
    ----------
    path : str
        file path for saved model
    generator_cls : nn.Module
        class used for the Generator
    discriminator_cls: nn.Module
        class used for the Discriminator/Critic
    map_location: callable | str | dict | None
        a function, torch.device, string or a dict specifying how to remap storage locations
    Returns
    -------
    G: generator_cls
        an element of the generator class with the architecture and weights from the saved model
    D: discriminator_cls
        an element of the discriminator class with the architecture and weights from the saved model
    training_configs: Dict
        configuration used for training
    """
    # when loading we use weights_only=False because the training loop will save activation functions
    # in G_config and D_config. Do not use this on a file not generated by train_gan or train_wgan_gp
    ckpt = torch.load(
        path,
        map_location=map_location,
        weights_only=False,
    )
    # validate that we have config and state dict for the models
    required_keys = {
        "G_config",
        "D_config",
        "G_state_dict",
        "D_state_dict"
        }
    missing = required_keys - ckpt.keys()
    if missing:
        raise KeyError(f"Checkpoint missing keys: {missing}")

    G = generator_cls(**ckpt["G_config"])
    D = discriminator_cls(**ckpt["D_config"])

    G.load_state_dict(ckpt["G_state_dict"])
    D.load_state_dict(ckpt["D_state_dict"])

    return G, D, ckpt.get("training_configs",{})

def cov_matrix(data : torch.Tensor, unbiased: bool = False):
    """
    Returns the covariance matrix of a batch of data
    Parameters
    ----------
    data : torch.Tensor
        tensor with dimensions (batch_size, num_features) that we 
        want to get covariance matrix for
    unbiased : bool
        whether we want unbiased estimator (divide by batch_size - 1)
    Returns
    -------
    torch.Tensor
        (num_features, num_features) matrix with the (i,j)th entry E((X_i-E(X_i))(X_j - E(X_j)))
    """
    if data.dim() != 2:
        raise ValueError("Data should be two dimensional (batch_size, num_features)")
    centered_data = data - data.mean(0, keepdim=True)
    batch_size = data.shape[0]
    if unbiased and batch_size < 2:
        raise ValueError("Can not use unbiased covariance with batch size < 2")
    divisor = batch_size - 1 if unbiased else batch_size
    return centered_data.T @ centered_data / divisor # has shape (num_features, num_features)

def cov_penalty(f_fake: torch.Tensor, f_real: torch.Tensor, unbiased: bool = False):
    """
    Compute the covariance/variance penalty term for feature matching
    Parameters
    ----------
    f_fake : torch.Tensor
        features from the fake data
    f_real : torch.Tensor
        features from the real data
    unbiased : bool
        whether or not to use unbiased statistics
    Returns
    torch.Tensor
        mean of sum of all variance differences and all covariance differences
    """
    cov_real = cov_matrix(f_real, unbiased)
    cov_fake = cov_matrix(f_fake, unbiased)
    # compute the square of the differences
    cov_diff = cov_real - cov_fake
    cov_diff_2 = cov_diff ** 2
    # get the upper triangular version so each covariance appears once
    cov_diff_2_upper = torch.triu(cov_diff_2)
    # get the correct number of entries
    num_features = cov_diff_2_upper.shape[0]
    divisor = num_features * (num_features + 1) // 2
    return cov_diff_2_upper.sum() / divisor

def feature_entropy(f_fake:torch.Tensor, unbiased=False, eps=1e-8):
    """
    computes the entropy of a sample in the feature space
    Parameters
    ----------
    f_fake : torch.Tensor
        sample in the feature space
    unbiased : bool
        whether to use biased or unbiased calculation for the covariance matrix
    eps : float
        size of term to be added for numerical stability
    Returns
    -------
    torch.Tensor
        -log (det Covariance matrix) (negative to maximize entropy)
    """
    feature_dim = f_fake.shape[1]
    cov = cov_matrix(f_fake, unbiased)
    s, logdet = torch.slogdet(cov + eps * torch.eye(feature_dim, device=f_fake.device))
    penalty = torch.tensor(1e6, device=f_fake.device)
    return torch.where(s > 0, -logdet / feature_dim, penalty)