"""
module with functions to save and load GAN models
"""
from typing import Callable, Type
import torch.nn as nn
import torch
from .models import Generator, Discriminator

def load_gan_checkpoint(
    path: str,
    generator_cls:Type[nn.Module] = Generator,
    discriminator_cls:Type[nn.Module] = Discriminator,
    map_location: Callable | str | dict | None = None,
):
    """
    function to read in saved models
    Parameters
    ----------
    path : str
        file path for saved model
    generator_cls : Type[nn.Module]
        class used for the Generator
    discriminator_cls: Type[nn.Module]
        class used for the Discriminator
    map_location: callable | str | dict | None
        a function, torch.device, string or a dict specifying how to remap storage locations
    Returns
    -------
    G: generator_cls
        an element of the generator class with the architecture and weights from the saved model
    D: discriminator_cls
        an element of the discriminator class with the architecture and weights from the saved model
    training_configs: Dict
        configuration used for training
    """
    # when loading we use weights_only=False because the training loop will save activation functions
    # in G_config and D_config. Do not use this on a file not generated by train_gan or train_wgan_gp
    ckpt = torch.load(
        path,
        map_location=map_location,
        weights_only=False,
    )
    # validate that we have config and state dict for the models
    required_keys = {
        "G_config",
        "D_config",
        "G_state_dict",
        "D_state_dict"
        }
    missing = required_keys - ckpt.keys()
    if missing:
        raise KeyError(f"Checkpoint missing keys: {missing}")

    G = generator_cls(**ckpt["G_config"])
    D = discriminator_cls(**ckpt["D_config"])

    G.load_state_dict(ckpt["G_state_dict"])
    D.load_state_dict(ckpt["D_state_dict"])

    return G, D, ckpt.get("training_configs",{})

def save_gan_checkpoint(
          save_path: str,
          G: Generator,
          D: Discriminator,
          training_configs: dict | None = None
          ):
    """
    function to save a Generator and Discriminator/Critic with optional training configs
    Parameters
    ----------
    save_path : str
        where to save the models
    G : Generator
        the Generator being saved
    D : Discriminator
        The Discriminator/Critic being saved
    training_configs Dict | None
        optional dict with configs used in training
    """
    torch.save({
        "training_configs": training_configs,
        "G_config": G.init_args,
        "D_config": D.init_args,
        "G_state_dict": G.state_dict(),
        "D_state_dict": D.state_dict()
        }, save_path)

